### ISSUE TITLE
Error Installing HIBAG

### ISSUE THREAD

**Issue by pbleic** [zhengxwen/HIBAG#15]
On R 4.1.2.  Have tried to install using BiocManager, using the dev version, and from source.  Each time have the same error:

LibHLA_ext_avx512vpopcnt.cpp: In function ‘int hamm_d(const TGenoStruct_512vpopcnt&, const HLA_LIB::THaplotype&, const HLA_LIB::THaplotype&)’:
LibHLA_ext_avx512vpopcnt.cpp:173:15: error: ‘_mm_popcnt_epi64’ was not declared in this scope

Can anyone suggest how to install?

**Comment by zhengxw-ab** [comment]
Please show me `sessionInfo()` and your GCC version.

**Comment by pbleic** [comment]
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocManager_1.30.16

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2

**Comment by zhengxw-ab** [comment]
The previous version (v1.28) of HIBAG does not contain `LibHLA_ext_avx512vpopcnt.cpp`.
http://bioconductor.org/packages/3.13/bioc/src/contrib/HIBAG_1.28.0.tar.gz

I guess the previous version should work.
Please use the previous version before I finally fix the issue.

**Comment by zhengxw-ab** [comment]
The new HIBAG_1.30.1.tar.gz is available at http://www.bioconductor.org/packages/release/bioc/html/HIBAG.html.
avx512vpopcnt requires GCC >= v8.0 to compile.
