### ISSUE TITLE
association test

### ISSUE THREAD

**Issue by SunYidan2021** [zhengxwen/HIBAG#19]
Hi Xiuwen,
I would like to ask how to understand the result of the association test. Is it necessary to calculate the Bonferroni-corrected p-values?
I also have some questions on convert alleles to Plink format. If I understand correctly, genotyped information is needed in this process. However, I would like to ask if it is possible to directly convert hlaAllele to Plink format.
Thank you in advance!

**Comment by zhengxwen** [comment]
Whether you need Bonferroni correction or not depends on your scientific question.
Try `hlaAlleleToVCF()` to convert hlaAllele to PLINK.
```
hlaAlleleToVCF(hla, outfn, DS=TRUE, verbose=TRUE)
```

**Comment by SunYidan2021** [comment]
Hi Xiuwen, 
I try to use this function, however, I got an error.
```Error in hlaAlleleToVCF() : could not find function "hlaAlleleToVCF"```

**Comment by zhengxwen** [comment]
Update the version of the HIBAG package.

CHANGES IN VERSION 1.28.0
-------------------------
    o new function `hlaAlleleToVCF()` for converting the imputed HLA classical alleles to a VCF file
