### ISSUE TITLE
Difference between h.pval and others

### ISSUE THREAD

**Issue by oalavijeh** [zhengxwen/HIBAG#32]
Dear colleage,

Many thanks for the fantastic tool. I was wondering what the difference between h.pval and the other p-values are? I appreciate there are differences between chi-squared and fishers but was unclear what the h.pval means when doing HLA association testing? 

![image](https://github.com/user-attachments/assets/e5d618ff-f352-48cd-90bd-479acbc7bc03)

Many thanks

**Comment by arsangjang** [comment]
Hello,

The chisq.p/fisher.p estimated from the chi-square test assess the hypothesis that the groups are independent (is there association between the two categorical variables? (or the distribution of one variable is independent of the distribution of the other variable)

However, the h.pval specifically tests the null hypothesis (H0) that the odds ratio is equal to 1, that obtained from Wald test/glm model.
